# .goreleaser.yml
builds:
  - id: iot_go-arm
    binary: iot_go
    main: ./cmd/cobra_main/main.go
    goos:
      - linux
    goarch:
      - arm
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_CFLAGS="--sysroot=/sysroot/linux/armhf -v -L/sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/lib"
      - CGO_LDFLAGS="--sysroot=/sysroot/linux/armhf -L/sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/lib"
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - C_INCLUDE_PATH=/sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/include
      - LIBRARY_PATH=/sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/lib
      - LD_LIBRARY_PATH=/sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/lib
      - CFLAGS="--sysroot=/sysroot/linux/armhf -v"
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -extldflags "--static -L/sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/lib" -w -X main.version={{.Version}}

  - id: iot_go-win
    binary: iot_go
    main: ./cmd/iot/main.go
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

before:
  hooks:
    - echo "Running pre-build hook"
    - ./build_arm_lib.sh

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
