package msg

type AutoGenerated struct {
	MsgType         string  `json:"msg_type"`
	GatewayNodeID   string  `json:"gateway_node_id"`
	HardwareVersion string  `json:"hardware_version"`
	SoftwareVersion string  `json:"software_version"`
	Rssi            int     `json:"rssi"`
	Ccid            string  `json:"ccid"`
	Custom          string  `json:"custom"`
	Project         string  `json:"project"`
	MqttIP          string  `json:"mqtt_ip"`
	MqttPort        int     `json:"mqtt_port"`
	MqttUserName    string  `json:"mqtt_user_name"`
	MqttPwd         string  `json:"mqtt_pwd"`
	Module1         Module1 `json:"module1"`
	Module2         Module2 `json:"module2"`
}
