# .github/workflows/release.yml
name: goreleaser

on:
  push:
    tags:
      - '*'
    # branches:
    #   - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version variable  
        run: |  
          if [ "${{ github.event_name }}" = "push" ] && [ ! -z "$(git describe --tags --exact-match 2>/dev/null)" ]; then
            VERSION=$(git describe --tags --exact-match)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "release" ]; then
            VERSION=${{ github.event.release.tag_name }}
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          else
            echo "No version found. Using default or branch name."
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g') # 使用分支名作为版本（可选）
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          fi
      -
        name: Set up Go
        uses: actions/setup-go@v5
      - name: Install ARM toolchain
        # run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf
        # 下载并解压 Linaro 工具链
        run: |
          # wget -q https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
          wget -q https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
          mv gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz /tmp/
          sudo mkdir -p /sysroot/linux
          sudo chmod -R 777 /sysroot/linux
          pushd /sysroot/linux
          tar -xf /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
          mv gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf armhf
          ls armhf
          ls armhf/arm-linux-gnueabihf/include/c++/6.5.0
          popd
          echo "--"
          ls /sysroot/linux/armhf/bin
          echo "---"
          ls /sysroot/linux/armhf
          echo "--"
          ls
          # export PATH=/tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin:$PATH
          # 将目录添加到 PATH, 不再支持
          # echo "::add-path::/tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin"
          # 假设我们想要将/path/to/your/directory添加到PATH中  
          echo "/sysroot/linux/armhf/bin:$PATH" >> $GITHUB_PATH
          cp /sysroot/linux/armhf/arm-linux-gnueabihf/libc/usr/lib/crt*.o .
          
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          # version: '~> v2'
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
